/* rename timestamped files to a more user-friedly version, replacing the
 * <millis> part with yyyy-mm-dd-hh-mm-ss.
 * 
 * 29.04.11 - new class
 * 
 * (C) 2011 fnh
 */

package hdbt.util;

import java.io.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;


/**
 * rename timestamped files from the auto-generated "millis" name to a
 * more user-friendly "yyyy-mm-dd-hh-mm-ss" format.
 */
public class RenameTimestampedFiles {
  
  public final static Pattern tsPattern = Pattern.compile(
     "1[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]" 
  );
  
  
  /** 
   * rename the given file. For example, the autogenerated filename
   * <code>/tmp/pa10-commandlog-1304067178463.xml</code> is parsed,
   * split into the components <code>/tmp/pa10-commandlog-</code>,
   * <code>1304067178463</code> and <code>.xml</code>.
   * This is then replaced by
   *  
   */
  public static void renameTimestampedFile( String filename ) {
    try {
      System.out.println( "-#- " + filename );
      
      Matcher m = tsPattern.matcher( filename );
      if ( !m.find() ) {
        System.out.println( "-W- no timestamp in filename '" + filename + "'" );
        return; 
      }
      
      String timestamp = filename.substring( m.start(), m.end() );
      
      String prettyName = 
        filename.substring( 0, m.start() )
        + TimeUtils.prettyFilename( Long.parseLong( timestamp ), null )
        + filename.substring( m.end() );
   
      System.out.println( "-I- rename to '" + prettyName + "'" );
     
      java.io.File f = new File( filename );
      if (!f.exists()) return;
      
      System.err.println( "-X- renaming not yet activated..." ); // FIXME
       // f.renameTo( new File( newName ));
    }
    catch( Exception e ) {
      e.printStackTrace(); 
    }
  }
  
  
  public static void usage() {
    System.out.println( 
      "Usage: java hdbt.util.RenameTimestampedFile <inputfile>\n" );
    System.exit( 1 );
  }
  
  
  public static void main( String args[] ) {
    //if (args.length == 0) usage();
    
    
    args = new String[] { // FIXME: selftest
"/tmp/pa10-commandlog-1304064984663.xml",
"/tmp/pa10Xggggggggggggggggggggg1304065081807.aaaaa15345354345.xml",
"/tmp/pa10-1304065217596.-1304065350492.xml",
"/tmp/pa10-commandlog-1304065350492.xml",
"/tmp/pa10-commandlog-1304065520486.xml",
"/tmp/1304065699944-pa10.xml",
"/tmp/joywarrior-1304065861030.xml",
    };

    for( String s : args ) {
      renameTimestampedFile( s );
    }
  }
  
}